#!/bin/bash

main() {
	local container_id="$1"; shift
	local port="$1"; shift
	local cmd="$@"

	local image="$(docker inspect -f "{{.Config.Image}}" $container_id)"
	local ip="$(docker inspect -f "{{.NetworkSettings.IPAddress}}" $container_id)"
    docker exec $container_id $cmd
}

main $@
